/* All sample interactions are ephemeral. No fetch, storage, payments or live forms. */
(() => {
  'use strict';
  const params=new URLSearchParams(location.search),sample=params.get('sample') || 'architecture-light';
  const thumbnail=params.has('thumbnail'),root=document.getElementById('experience');
  const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const asset=name=>'../assets/previews/'+name;
  const notify=type=>parent.postMessage({channel:'portfolio-preview',type},'*');
  const isInvite=['safari','housewarming'].includes(sample);
  let steps=[],tip=0,guiding=!thumbnail,feedbackTimer;
  function feedback(text){$('feedback').textContent=text;$('feedback').hidden=false;clearTimeout(feedbackTimer);feedbackTimer=setTimeout(()=>$('feedback').hidden=true,4500);}
  function clearHighlight(){document.querySelectorAll('.guided-target').forEach(el=>el.classList.remove('guided-target'));}
  function guide(scroll=false){
    if(thumbnail)return;
    const focusHidden=guiding?document.activeElement===$('tour-restore'):$('tour').contains(document.activeElement);
    clearHighlight();$('tour').hidden=!guiding||thumbnail;$('tour-restore').hidden=guiding||thumbnail;
    if(focusHidden)(guiding?$('tour-dismiss'):$('tour-restore')).focus({preventScroll:true});
    if(!guiding||!steps.length||thumbnail)return;
    const step=steps[tip];$('tour-count').textContent=`DICA ${tip+1} / ${steps.length}`;$('tour-title').textContent=step.title;$('tour-text').textContent=step.text;
    $('tour-back').disabled=tip===0;$('tour-next').textContent=tip===steps.length-1?'Explorar livremente ✓':'Próxima dica →';
    const target=document.querySelector(step.target);if(target){target.classList.add('guided-target');if(scroll)target.scrollIntoView({block:'center',behavior:'auto'});}
  }
  function goTip(next){if(next>=steps.length){guiding=false;guide();return;}if(isInvite&&document.querySelector('.cover-skip'))document.querySelector('.cover-skip').click();tip=Math.max(0,next);steps[tip].prepare?.();guide(true);}
  $('tour-next').addEventListener('click',()=>goTip(tip+1));$('tour-back').addEventListener('click',()=>goTip(tip-1));
  $('tour-dismiss').addEventListener('click',()=>{guiding=false;guide();});$('tour-restore').addEventListener('click',()=>{guiding=true;guide(true);});
  window.addEventListener('message',e=>{if(e.source===parent&&e.data?.channel==='portfolio-preview'&&e.data.type==='guide'){guiding=true;guide(true);}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){const inner=document.querySelector('dialog[open]');if(inner){e.preventDefault();inner.close();}else notify('close');}});
  function nav(){
    const b=$('sample-menu');if(b)b.addEventListener('click',()=>{const open=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(open));$('sample-nav').hidden=!open;});
    document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const el=document.querySelector(a.getAttribute('href'));if(el){e.preventDefault();el.scrollIntoView({behavior:'auto'});if($('sample-nav'))$('sample-nav').hidden=true;if(b)b.setAttribute('aria-expanded','false');}}));
  }
  // A sandbox without allow-forms blocks native submission before submit handlers.
  // Explicit buttons/Enter keep demos interactive without enabling form requests.
  function localForm(id,action){
    const form=$(id),button=form.querySelector('button[type="submit"]');
    const run=e=>{e.preventDefault();action();};
    form.addEventListener('submit',run);
    button.type='button';button.addEventListener('click',run);
    form.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.tagName==='INPUT'){run(e);}});
  }
  function architecture(){
    const warm=sample==='architecture-warm';document.body.className=warm?'architecture warm':'architecture';
    const brand=warm?'habitar.':'FORMA<span>®</span>',heroImage=warm?'architecture-interior.jpg':'architecture-house.jpg';
    root.innerHTML=`<header class="arch-nav"><a class="arch-brand" href="#arch-home">${brand}</a><button id="sample-menu" aria-label="Abrir navegação" aria-expanded="false" aria-controls="sample-nav">☰</button><nav id="sample-nav" hidden><a href="#arch-projects">Projetos</a><a href="#arch-about">O estúdio</a><a href="#arch-contact">Contato</a></nav></header>
    <section class="arch-hero" id="arch-home"><div class="arch-copy"><span class="eyebrow">${warm?'Arquitetura de interiores':'Arquitetura · Design · Essência'}</span><h1>${warm?'Espaços para<br><em>sentir.</em>':'Menos excesso.<br>Mais <em>essência.</em>'}</h1><p>${warm?'A beleza de morar no seu próprio ritmo.':'Arquitetura que encontra beleza no essencial.'}</p><a class="arch-cta" href="#arch-projects">Explore os projetos <span>↘</span></a></div><figure class="arch-hero-image"><img src="${asset(heroImage)}" alt="${warm?'Interior com materiais naturais e móveis claros':'Fachada residencial clara com jardim'}"><figcaption>${warm?'Luz, textura & afeto':'Forma, luz & matéria'} <span>01 / 02</span></figcaption></figure></section>
    <section id="arch-projects" class="arch-section"><div class="eyebrow">O olhar em cada detalhe</div><h2>${warm?'Ambientes que abraçam.':'Uma nova perspectiva.'}</h2><div class="arch-filters" aria-label="Filtrar projetos"><button data-filter="all" aria-pressed="true">Todos</button><button data-filter="residencial" aria-pressed="false">Residencial</button><button data-filter="interiores" aria-pressed="false">Interiores</button></div><div class="arch-projects">
    <button class="arch-project" data-category="residencial" data-name="Luz & forma" data-photo="architecture-house.jpg"><img src="${asset('architecture-house.jpg')}" alt="Fachada residencial" loading="lazy"><span><strong>Luz & forma</strong><small>Residencial</small><b>↗</b></span></button>
    <button class="arch-project" data-category="interiores" data-name="Refúgio natural" data-photo="architecture-interior.jpg"><img src="${asset('architecture-interior.jpg')}" alt="Sala com sofá e madeira natural" loading="lazy"><span><strong>Refúgio natural</strong><small>Interiores</small><b>↗</b></span></button></div></section>
    <section id="arch-about" class="arch-about"><span class="eyebrow">Nosso processo</span><h2>O espaço começa<br>com uma conversa.</h2><p>Escutar. Desenhar. Transformar. Um caminho que conecta rotina, materiais e a maneira de viver cada ambiente.</p><ol><li><span>01</span> Escuta & conceito</li><li><span>02</span> Projeto & materialidade</li><li><span>03</span> Detalhes & execução</li></ol></section>
    <section id="arch-contact" class="arch-section"><span class="eyebrow">Vamos criar juntos</span><h2>Qual é o seu<br>próximo espaço?</h2><form id="arch-form"><label for="arch-type">Tipo de projeto</label><select id="arch-type"><option>Residencial</option><option>Interiores</option><option>Comercial</option></select><button class="solid" type="submit">Iniciar uma conversa ↗</button><p id="arch-success" hidden role="status">Conversa simulada! Em um site completo, esta escolha segue para o atendimento do escritório.</p></form></section><footer class="sample-footer">${warm?'habitar.':'FORMA'} <span>Experiência de navegação</span><small>Fotografias: Wes Fischer e Lui Peng / Unsplash</small></footer>
    <dialog id="detail-dialog" class="arch-detail"><button id="detail-close" aria-label="Fechar galeria">✕</button><h2 id="detail-title"></h2><img id="detail-image" alt="Imagem de arquitetura"><p id="detail-caption"></p><div class="gallery-controls"><button id="gallery-prev" aria-label="Imagem anterior">←</button><span id="gallery-counter">1 / 2</span><button id="gallery-next" aria-label="Próxima imagem">→</button></div></dialog>`;
    nav();let galleryIndex=0,selectedCard;
    const photos=['architecture-house.jpg','architecture-interior.jpg'];
    const updateImage=()=>{$('detail-image').src=asset(photos[galleryIndex]);$('detail-caption').textContent=galleryIndex===0?'Luz natural e linhas da fachada.':'Madeira, textura e aconchego no interior.';$('gallery-counter').textContent=`${galleryIndex+1} / 2`;};
    document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('.arch-project').forEach(p=>p.hidden=b.dataset.filter!=='all'&&p.dataset.category!==b.dataset.filter);}));
    document.querySelectorAll('.arch-project').forEach(b=>b.addEventListener('click',()=>{selectedCard=b;galleryIndex=photos.indexOf(b.dataset.photo);$('detail-title').textContent=b.dataset.name;updateImage();$('detail-dialog').showModal();}));
    $('gallery-next').addEventListener('click',()=>{galleryIndex=(galleryIndex+1)%2;updateImage();});$('gallery-prev').addEventListener('click',()=>{galleryIndex=(galleryIndex+1)%2;updateImage();});
    $('detail-close').addEventListener('click',()=>$('detail-dialog').close());$('detail-dialog').addEventListener('close',()=>selectedCard?.focus());
    localForm('arch-form',()=>{$('arch-success').hidden=false;});
    steps=[{target:'.arch-cta',title:'Entre no portfólio',text:'Toque em “Explore os projetos” para conhecer os ambientes.'},{target:'.arch-filters',title:'Encontre o seu estilo',text:'Os filtros separam residências e interiores. Experimente trocar a categoria.'},{target:'.arch-projects',title:'Veja além da capa',text:'Abra um projeto e use as setas para navegar pela galeria de imagens.'},{target:'#arch-form',title:'Da inspiração ao contato',text:'Escolha o tipo de projeto e simule o início de uma conversa. Nenhuma mensagem será enviada.'}];
  }
  function law(){
    document.body.className='law';const mobile=sample==='law-mobile';
    const scales='<svg viewBox="0 0 320 320" fill="none" stroke="currentColor" aria-label="Balança da justiça" role="img"><circle cx="160" cy="35" r="5"/><path d="M160 40v242M74 282h172M40 90h240M68 90 23 195h90L68 90Zm184 0-45 105h90L252 90ZM23 195a45 35 0 0 0 90 0m94 0a45 35 0 0 0 90 0" stroke-width="1.4"/></svg>';
    root.innerHTML=`<header class="law-nav"><a class="law-brand" href="#law-home"><strong>F&M</strong><span>FERREIRA E MOREIRA<small>ADVOGADOS ASSOCIADOS</small></span></a><button id="sample-menu" aria-label="Abrir navegação" aria-expanded="false" aria-controls="sample-nav">☰</button><nav id="sample-nav" hidden><a href="#law-about">O escritório</a><a href="#law-areas">Atuação</a><a href="#law-contact">Contato</a></nav><div class="law-desktop-nav"><a href="#law-about">O escritório</a><a href="#law-areas">Atuação</a><a href="#law-contact">Contato</a></div></header>
    <section class="law-hero" id="law-home"><div><span class="eyebrow">Orientação para pessoas e negócios</span><h1>Clareza para decidir.<br><em>Segurança para seguir.</em></h1><p>Orientação jurídica próxima e criteriosa, com atenção às particularidades de cada pessoa e de cada negócio.</p><a class="gold-button" href="#law-contact">Entre em contato ↗</a><small>Escuta atenta. Análise cuidadosa. Comunicação clara.</small></div><div class="law-symbol">${scales}<span>Compromisso com o direito</span></div></section>
    <section id="law-areas" class="law-section"><span class="eyebrow">Áreas de atuação</span><h2>Como podemos ajudar</h2><div class="law-areas">${[['civil','Direito Civil','Contratos, responsabilidades e relações civis.','Informações organizadas para entender as possibilidades de atendimento em relações e contratos.'],['trabalhista','Direito Trabalhista','Orientação nas relações de trabalho.','Uma apresentação clara da área, com espaço para explicar como funciona o atendimento.'],['empresarial','Direito Empresarial','Apoio jurídico à rotina dos negócios.','Uma visão dos serviços de orientação empresarial, organização de contratos e acompanhamento.']].map(([id,title,desc,more],i)=>`<article><button data-area="${id}" aria-expanded="false" aria-controls="area-${id}"><span>0${i+1}</span><h3>${title}</h3><p>${desc}</p><b aria-hidden="true">+</b></button><div id="area-${id}" class="area-detail" hidden>${more}</div></article>`).join('')}</div></section>
    <section id="law-about" class="law-section law-about"><div><span class="eyebrow">O escritório</span><h2>Direito com atenção<br>às pessoas.</h2></div><div><p>Relações baseadas na escuta, no cuidado e na transparência. Cada demanda merece uma análise individual e uma orientação compreensível.</p><div class="law-values"><span>01 / Escuta</span><span>02 / Clareza</span><span>03 / Confiança</span></div></div></section>
    <section id="law-contact" class="law-contact"><div><span class="eyebrow">Entre em contato</span><h2>Vamos conversar?</h2><p>Um caminho simples para iniciar o atendimento.</p><button id="law-whatsapp" class="gold-button">Falar pelo WhatsApp ↗</button></div><form id="law-form"><label for="law-topic">Área de interesse</label><select id="law-topic"><option>Direito Civil</option><option>Direito Trabalhista</option><option>Direito Empresarial</option></select><label for="law-message">Sua mensagem</label><textarea id="law-message" rows="3" maxlength="400" placeholder="Experimente escrever uma mensagem…"></textarea><button class="gold-button" type="submit">Simular envio ↗</button><p id="law-success" hidden role="status">Envio simulado. Nenhuma informação foi transmitida. No site completo, o pedido segue para o canal do escritório.</p></form></section><footer class="sample-footer"><span>F&M · Advocacia</span><span>Prévia de navegação</span></footer>`;
    nav();document.querySelectorAll('[data-area]').forEach(b=>b.addEventListener('click',()=>{const open=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(open));$('area-'+b.dataset.area).hidden=!open;}));
    localForm('law-form',()=>{$('law-success').hidden=false;});$('law-whatsapp').addEventListener('click',()=>feedback('Na versão completa, este botão abre o WhatsApp do escritório. Aqui, a conversa é apenas demonstrada.'));
    steps=[{target:'.gold-button',title:'Um caminho direto ao atendimento',text:'O botão leva até a área de contato. Experimente tocar.'},{target:'.law-areas',title:'Áreas que se abrem ao toque',text:'Escolha uma área para expandir a explicação, sem sair da página.'},{target:'#law-about',title:'Apresente o escritório',text:'Uma seção para comunicar o posicionamento e o jeito de atender.'},{target:'#law-form',title:'Experimente o formulário',text:'Selecione uma área e simule o envio. Nada é enviado para um escritório real.'}];
    if(mobile)document.body.classList.add('law-mobile');
  }
  let inviteState={name:'Visitante',company:0,gift:'Presença'},inviteStep=0;
  function invitation(){
    document.body.className=sample==='safari'?'invite safari':'invite housewarming';
    const safari=sample==='safari';
    root.innerHTML=`<header class="invite-nav"><span>${safari?'✳ SAFARI':'⌂ CASA NOVA'}</span><small>Um convite para celebrar</small></header><section class="invitation"><div id="invite-content"></div>${safari?`<aside class="safari-scene"><span>UMA GRANDE AVENTURA<small>para um dia inesquecível</small></span><img src="${asset('safari/mickey-safari.webp')}" alt="Mickey com roupa de explorador safari"><p>O mundo é enorme.<br><em>A alegria de celebrar também.</em></p></aside>`:''}</section><footer class="sample-footer">${safari?'FEITO DE AMOR & UM POUQUINHO DE MAGIA':'UM NOVO LAR. NOVAS MEMÓRIAS.'}<span>Convite interativo</span></footer>`;
    steps=[{target:'[data-action="start"]',title:'Abra o seu convite',text:'Uma entrada especial para dar o tom da comemoração.',prepare:()=>renderInvite(0)},{target:'#guest-name',title:'Uma experiência pessoal',text:'O nome personaliza as próximas telas. Use o exemplo “Visitante”; nenhum cadastro será salvo.',prepare:()=>renderInvite(1)},{target:'.company-options',title:'Organize quem vem junto',text:'Escolha uma opção para experimentar o fluxo de acompanhantes.',prepare:()=>renderInvite(2)},{target:'.gift-options',title:'Presentes sem complicação',text:'Toque em um presente ou escolha apenas levar seu carinho. A seleção é uma simulação.',prepare:()=>renderInvite(3)},{target:'#review-card',title:'Revise antes de confirmar',text:'Veja as escolhas e toque em “Simular confirmação”. Nenhuma presença real é registrada.',prepare:()=>renderInvite(4)},{target:'#confirmation',title:'O convite continua aqui',text:'Experimente os botões de localização e agenda. Os dados reais do evento foram removidos.',prepare:()=>renderInvite(5)}];
    renderInvite(0);
    if(safari){
      const css=document.createElement('link');css.rel='stylesheet';css.href='envelope.css';document.head.append(css);
      const script=document.createElement('script');script.src='envelope.js';document.body.append(script);
      document.addEventListener('envelope-opened',()=>{tip=0;steps[0].target='[data-action="start"]';steps[0].title='Vamos à aventura';steps[0].text='Agora experimente a confirmação de presença, passo a passo.';renderInvite(0);guide();},{once:true});
      if(!thumbnail){steps[0].target='#envelopeSeal';steps[0].title='Toque no lacre do envelope';steps[0].text='O envelope se abre em uma animação. Depois, toque em “Entrar na aventura”.';}
      script.addEventListener('load',()=>guide());
    }
  }
  function renderInvite(step){
    inviteStep=step;const safari=sample==='safari';const container=$('invite-content');
    const header=`<span class="eyebrow">${step?`PASSO ${Math.min(step,4)} / 4`:'VOCÊ RECEBEU UM CONVITE ESPECIAL'}</span>`;
    const back=`<button class="text-button" data-action="back">← Voltar</button>`;
    let content='';
    if(step===0) content=`<div class="invite-welcome">${!safari?'<span class="house-emblem">⌂</span>':''}${header}<h1>${safari?'Meu primeiro<br><em>safari.</em>':'Chá de<br><em>Casa Nova</em>'}</h1><div class="invitation-rule"></div><p>${safari?'Um aniversário cheio de descobertas, sorrisos e muita aventura.':'Um novo lar. Um novo capítulo.<br>Vamos celebrar com quem faz parte da nossa história.'}</p><div class="event-info"><span>Uma data especial</span><span>Um lugar para celebrar</span></div><button class="solid" data-action="start">${safari?'Vamos à aventura':'Abrir convite'} ↗</button></div>`;
    if(step===1)content=`${header}<h2>A celebração fica<br>melhor <em>com você.</em></h2><p>Como podemos te chamar?</p><form id="guest-form"><label for="guest-name">Nome na prévia</label><input id="guest-name" autocomplete="off" maxlength="60" value="${esc(inviteState.name)}" required><p id="guest-error" class="form-error" role="alert" hidden>Digite um nome para continuar.</p><div class="invite-actions">${back}<button class="solid" type="submit">Continuar →</button></div><small>Use um nome de exemplo. As informações ficam somente nesta prévia.</small></form>`;
    if(step===2)content=`${header}<h2>Quem vem<br><em>com você?</em></h2><p>A organização começa nos pequenos detalhes.</p><div class="company-options"><button data-company="0" aria-pressed="${inviteState.company===0}"><span>◎</span> Vou sem acompanhantes</button><button data-company="1" aria-pressed="${inviteState.company===1}"><span>◎◎</span> Vou com 1 acompanhante</button><button data-company="2" aria-pressed="${inviteState.company===2}"><span>◎◎◎</span> Vou com 2 acompanhantes</button></div>${back}`;
    if(step===3)content=`${header}<h2>Pequenos presentes.<br><em>Grandes memórias.</em></h2><p>Sua presença já é especial. Escolha uma opção para testar.</p><div class="gift-options">${(safari?[['Livro de histórias','📖'],['Brinquedo educativo','🧩'],['Roupa infantil','☀']]:[['Conjunto de copos','gift-glasses.webp'],['Batedeira','gift-mixer.webp'],['Toalhas','gift-towels.webp']]).map(([name,img])=>`<button data-gift="${name}" aria-pressed="${inviteState.gift===name}">${/\.(png|webp)$/.test(img)?`<img src="${asset(img)}" alt="${name}">`:`<span class="gift-symbol">${img}</span>`}<strong>${name}</strong></button>`).join('')}<button class="presence-choice" data-gift="Presença" aria-pressed="${inviteState.gift==='Presença'}">♡ Vou levar meu carinho</button></div><div class="invite-actions">${back}<button class="solid" data-action="review">Revisar escolhas →</button></div>`;
    if(step===4)content=`${header}<h2>Tudo pronto<br><em>para celebrar?</em></h2><div id="review-card" class="review-card"><div><span>Convidado</span><strong>${esc(inviteState.name)}</strong></div><div><span>Acompanhantes</span><strong>${inviteState.company}</strong></div><div><span>Seu carinho</span><strong>${esc(inviteState.gift)}</strong></div></div><div class="invite-actions">${back}<button class="solid" data-action="confirm">Simular confirmação ✓</button></div><small>Este teste não registra presença em nenhum evento.</small>`;
    if(step===5)content=`<div id="confirmation"><span class="success-ring">✓</span><span class="eyebrow">EXPERIÊNCIA CONCLUÍDA</span><h2>Que bom ter<br><em>você por aqui.</em></h2><p>${esc(inviteState.name)}, sua confirmação foi simulada.</p><div class="event-actions"><button data-action="location">⌖ Como chegar</button><button data-action="calendar">▦ Salvar na agenda</button></div><p class="event-note">No convite completo, estes atalhos mostram o local e a data escolhidos para o evento.</p><button class="solid" data-action="reset">Experimentar de novo ↺</button></div>`;
    container.innerHTML=content;
    container.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;if(a==='start')setInvite(1);if(a==='back')setInvite(Math.max(0,inviteStep-1));if(a==='review')setInvite(4);if(a==='confirm')setInvite(5);if(a==='reset'){inviteState={name:'Visitante',company:0,gift:'Presença'};setInvite(0);}if(a==='location')feedback('Aqui o convidado abriria o mapa. O endereço real foi removido desta prévia.');if(a==='calendar')feedback('Aqui o evento seria salvo na agenda. Data e horário reais foram removidos.');}));
    if($('guest-form'))localForm('guest-form',()=>{const value=$('guest-name').value.trim();if(!value){$('guest-error').hidden=false;return;}inviteState.name=value;setInvite(2);});
    container.querySelectorAll('[data-company]').forEach(b=>b.addEventListener('click',()=>{inviteState.company=Number(b.dataset.company);setInvite(3);}));
    container.querySelectorAll('[data-gift]').forEach(b=>b.addEventListener('click',()=>{inviteState.gift=b.dataset.gift;container.querySelectorAll('[data-gift]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}));
  }
  function setInvite(step){tip=step;renderInvite(step);guide();if(!thumbnail){const h=$('invite-content').querySelector('h1,h2');h.tabIndex=-1;h.focus({preventScroll:true});h.scrollIntoView({block:'start'});}}
  const allowed=['architecture-light','architecture-warm','law-mobile','law-desktop','safari','housewarming'];
  if(!allowed.includes(sample)){root.innerHTML='<p>Prévia não encontrada. Feche esta janela e escolha outra experiência.</p>';$('tour').hidden=true;notify('ready');return;}
  if(sample.startsWith('architecture'))architecture();else if(sample.startsWith('law'))law();else invitation();
  if(thumbnail){document.body.classList.add('thumbnail');$('tour').remove();$('tour-restore').remove();document.documentElement.inert=true;}else guide();
  notify('ready');
})();
